server:
  port: 9000
spring:
  application:
    name: service-provider
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2182

  mydatasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/actsystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: rz37873@#
#  redis:
#    host: 127.0.0.1
#    port: 6379
  kafka:
    radius:
      consumer:
        bootstrap-servers: 127.0.0.1:9092
        group-id: test1
      producer:
        bootstrap-servers: 127.0.0.1:9092

mybatis:
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    logger: slf4j
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk
    address: zookeeper://127.0.0.1:2182